/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorVentanaAsignatura;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorVentanaCrearCurso;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorVentanaDocente;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Docente;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.SesionCurso;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.enumeraciones.DiaEnum;

/**
 *
 * @author dir_software
 */
public class VentanaCrearCurso extends javax.swing.JInternalFrame {

	private ControladorVentanaCrearCurso controlador;
	private ControladorVentanaAsignatura controladorAsig;
	private ControladorVentanaDocente controladorDoc;
	private Asignatura asignatura;
	private Docente docente;
	private Curso curso;

	/**
	 * Creates new form VentanaCrearCurso
	 */
	public VentanaCrearCurso() {
		controlador = new ControladorVentanaCrearCurso();
		controladorAsig = new ControladorVentanaAsignatura();
		controladorDoc = new ControladorVentanaDocente();
		asignatura = null;
		docente = null;
		curso = null;
		initComponents();
		setClosable(true);
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		cargarComboDia();
		limpiarTabla();

	}

	/**
	 * método que limpia la tabla
	 */
	private void limpiarTabla() {
		DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
		tabla.setRowCount(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodigoasignatura = new javax.swing.JTextField();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnombreasignatura = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfceduladocente = new javax.swing.JTextField();
        btnBuscarBuscarDocente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfnombredocente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboDia = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        comboHoraInicio = new javax.swing.JComboBox();
        comboHoraFin = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorario = new javax.swing.JTable();
        btnAgregarSesion = new javax.swing.JButton();
        btnQuitarSesion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        brtnEditar = new javax.swing.JButton();

        setTitle("Administrar Curso");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/class.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel1.setText("Codigo");

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        tfnombreasignatura.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcodigoasignatura)
                    .addComponent(tfnombreasignatura))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Docente"));

        jLabel3.setText("Cedula");

        btnBuscarBuscarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarBuscarDocente.setToolTipText("Buscar Docente");
        btnBuscarBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBuscarDocenteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        tfnombredocente.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfceduladocente)
                    .addComponent(tfnombredocente))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarBuscarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfceduladocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfnombredocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario Asignatura"));

        jLabel5.setText("Dia");

        jLabel6.setText("Hora Inicio:");

        comboHoraInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una hora", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        comboHoraInicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboHoraInicioItemStateChanged(evt);
            }
        });

        jLabel7.setText("Hora Fin:");

        tablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dia", "Hora Inicial", "Hora Final"
            }
        ));
        jScrollPane1.setViewportView(tablaHorario);

        btnAgregarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
        btnAgregarSesion.setToolTipText("Agregar sesion");
        btnAgregarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSesionActionPerformed(evt);
            }
        });

        btnQuitarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation.png"))); // NOI18N
        btnQuitarSesion.setToolTipText("Quitar Sesion");
        btnQuitarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitarSesion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(comboHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAgregarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuitarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
        btnCrear.setToolTipText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        brtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen38.png"))); // NOI18N
        brtnEditar.setToolTipText("Editar");
        brtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
		try {
			if (tfcodigoasignatura.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Porfavor ingresar el código de " + "una asignatura");
			}
			String codigo = tfcodigoasignatura.getText();
			asignatura = controladorAsig.buscar(codigo);

			if (asignatura == null) {
				JOptionPane.showMessageDialog(null, "No se encontro una asignatura " + "con este codigo: " + codigo);
			} else {
				tfnombreasignatura.setText(asignatura.getNombre());
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, "Ocurrio un error buscando la asignatura", "Error",
					JOptionPane.ERROR_MESSAGE);
			ex.getStackTrace();
		}
	}// GEN-LAST:event_btnBuscarAsignaturaActionPerformed

	private void btnBuscarBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarBuscarDocenteActionPerformed
		try {
			if (tfceduladocente.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Porfavor ingresar la cedula de " + "un docente");
			} else {
				String ced = tfceduladocente.getText();

				docente = controladorDoc.buscarDocente(ced);

				if (docente == null) {
					JOptionPane.showMessageDialog(null, "No se encontro un docente " + "con esta cedula: " + ced);
				} else {
					tfnombredocente.setText(docente.getNombre() + " " + docente.getApellido());
				}
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, "Ocurrio un error buscando el docente", "Error",
					JOptionPane.ERROR_MESSAGE);
			ex.getStackTrace();
		}
	}// GEN-LAST:event_btnBuscarBuscarDocenteActionPerformed

	private void btnAgregarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarSesionActionPerformed

		if (comboDia.getSelectedIndex() == 0 || comboHoraInicio.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(null, "Porfavor seleccionar el dia, " + "hora de inicio y de finalización");
		} else {
			DiaEnum dia = (DiaEnum) comboDia.getSelectedItem();
			int horaInicio = Integer.parseInt((String) comboHoraInicio.getSelectedItem());
			int horaFin = (Integer) comboHoraFin.getSelectedItem();
			boolean entro=false;
			for (int i = 0; i < tablaHorario.getRowCount(); i++) {
				DiaEnum primer = (DiaEnum) tablaHorario.getValueAt(i, 0);
				int se= (Integer) tablaHorario.getValueAt(i, 1);
				int ter=(Integer) tablaHorario.getValueAt(i, 2);
				if(dia.equals(primer)&&se<=horaInicio&&horaInicio<ter){
					entro=true;
				}
			}
			if(!entro){
			DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
				tabla.addRow(new Object[] { dia, horaInicio, horaFin });
			}else{
				JOptionPane.showMessageDialog(null,"No puede agregar esta sesion ya que hay un cruce de horarios.");
			}
		}

	}// GEN-LAST:event_btnAgregarSesionActionPerformed

	private void btnQuitarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuitarSesionActionPerformed
		DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
		if (tabla.getRowCount() != 0) {
			int c = tablaHorario.getSelectedRow();
			tabla.removeRow(c);
		}
	}// GEN-LAST:event_btnQuitarSesionActionPerformed

	private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearActionPerformed
		try {
			if (docente == null && asignatura == null) {
				JOptionPane.showMessageDialog(null,
						"Porfavor busque un docente y " + "una asignatura para crear el curso");
			 //}else if (tfCodigoCurso.getText().isEmpty()) {
				//JOptionPane.showMessageDialog(null, "Ingrese el codigo del curso");
			} else {
				// se crea el curso con sus atributos

				curso = new Curso(null, docente, asignatura);

				// se le agregan las sesiones que están en la tabla al curso
				List<SesionCurso> sesiones = new ArrayList<SesionCurso>();
				DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
				for (int i = 0; i < tabla.getRowCount(); i++) {
					DiaEnum dia = (DiaEnum) tabla.getValueAt(i, 0);
					int fechaInicio = (Integer) tabla.getValueAt(i, 1);
					int fechaFin = (Integer) tabla.getValueAt(i, 2);
					SesionCurso sesion = new SesionCurso(curso, dia, fechaInicio, fechaFin);
					sesiones.add(sesion);
					curso.setSesiones(sesiones);
				}
				controlador.crearCurso(curso);
				JOptionPane.showMessageDialog(null, "El curso ha sido creado " + "exitosamente");
			}
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			exc.printStackTrace();
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(null, "Ocurrio un error creando el curso", "Error",
					JOptionPane.ERROR_MESSAGE);
			exc.printStackTrace();
		}
	}// GEN-LAST:event_btnCrearActionPerformed

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
		try {
			if (asignatura == null || docente == null) {
				JOptionPane.showMessageDialog(null,
						"Porfavor primero busque el " + "código de la asignatura y la cedula del docente");
			} else {
				curso = controlador.buscarCurso(asignatura, docente);
				List<SesionCurso> lista = curso.getSesiones();
				if (lista == null) {
					JOptionPane.showMessageDialog(null, "El curso no tiene sesiones");
				} else {
					DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
					tabla.setRowCount(0);
					for (SesionCurso sesion : lista) {
						tabla.addRow(new Object[] { sesion.getDia(), sesion.getHoraInicio(), sesion.getHoraFinal() });
					}
				}
			}

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			ex.getStackTrace();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, "Ocurrio un error buscando el curso", "Error",
					JOptionPane.ERROR_MESSAGE);
			ex.getStackTrace();
		}
	}// GEN-LAST:event_btnBuscarActionPerformed

	private void brtnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_brtnEditarActionPerformed
		try {
			if (docente == null || asignatura == null) {
				JOptionPane.showMessageDialog(null, "Porfavor primero busque la " + "la asignatura y el docente");
			} else {
				List<SesionCurso> sesiones = new ArrayList<SesionCurso>();
				DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
				for (int i = 0; i < tabla.getRowCount(); i++) {
					DiaEnum dia = (DiaEnum) tabla.getValueAt(i, 0);
					int fechaInicio = (Integer) tabla.getValueAt(i, 1);
					int fechaFin = (Integer) tabla.getValueAt(i, 2);
					SesionCurso sesion = new SesionCurso(curso, dia, fechaInicio, fechaFin);
					sesiones.add(sesion);
					curso.setDocente(docente);
					curso.setAsignatura(asignatura);
					curso.setSesiones(sesiones);
				}
				controlador.editarCurso(curso);
				JOptionPane.showMessageDialog(null, "El curso ha sido editado " + "exitosamente");
			}
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			ex.getStackTrace();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, "Ocurrio un error editando el curso", "Error",
					JOptionPane.ERROR_MESSAGE);
			ex.getStackTrace();
		}
	}// GEN-LAST:event_brtnEditarActionPerformed

	private void comboHoraInicioItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboHoraInicioItemStateChanged
		if (comboHoraInicio.getSelectedIndex() == 0) {
			comboHoraFin.removeAllItems();
			comboHoraFin.addItem("Seleccione la hora inicio");
		} else {
			comboHoraFin.removeAllItems();
			int horaInicio = Integer.parseInt((String) comboHoraInicio.getSelectedItem());
			int horaFinal0 = horaInicio + 1;
			int horaFinal1 = horaInicio + 2;
			int horaFinal2 = horaInicio + 3;
			int horaFinal3 = horaInicio + 4;
			int horaFinal4 = horaInicio + 5;
			comboHoraFin.addItem(horaFinal0);
			comboHoraFin.addItem(horaFinal1);
			comboHoraFin.addItem(horaFinal2);
			comboHoraFin.addItem(horaFinal3);
			comboHoraFin.addItem(horaFinal4);
		}
	}// GEN-LAST:event_comboHoraInicioItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtnEditar;
    private javax.swing.JButton btnAgregarSesion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JButton btnBuscarBuscarDocente;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnQuitarSesion;
    private javax.swing.JComboBox comboDia;
    private javax.swing.JComboBox comboHoraFin;
    private javax.swing.JComboBox comboHoraInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHorario;
    private javax.swing.JTextField tfceduladocente;
    private javax.swing.JTextField tfcodigoasignatura;
    private javax.swing.JTextField tfnombreasignatura;
    private javax.swing.JTextField tfnombredocente;
    // End of variables declaration//GEN-END:variables

	/**
	 * carga el combo con los dias de la semana que estan en la clase enumerada
	 * DiaEnum
	 */
	public void cargarComboDia() {
		comboDia.removeAllItems();
		DiaEnum[] dias = DiaEnum.values();
		comboDia.addItem("Seleccione un día");
		for (int i = 0; i < dias.length; i++) {
			DiaEnum tipo = dias[i];
			comboDia.addItem(tipo);
		}
	}
}
