/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorVentanaIngresarCalificaciones;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Docente;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Estudiante;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Evaluacion;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Nota;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.RegistroCurso;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dir_software
 */
public class VentanaIngresarCalificaciones extends javax.swing.JInternalFrame {

    /**
     * El controlador de la ventana ingresar calificaciones
     */
    private ControladorVentanaIngresarCalificaciones controlador;

    /**
     * Creates new form VentanaIngresarCalificaciones
     */
    public VentanaIngresarCalificaciones() {
        controlador = new ControladorVentanaIngresarCalificaciones();
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);
        setClosable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfceduladocente = new javax.swing.JTextField();
        btnBuscarAsignatura1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfnombredocente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        comboCurso = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combocalificacion = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCalificaicon = new javax.swing.JTable();
        btnCalificar = new javax.swing.JButton();

        setTitle("Ingresar Calificaiones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check44.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Docente"));

        jLabel3.setText("Cedula");

        btnBuscarAsignatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura1.setToolTipText("Buscar Docente");
        btnBuscarAsignatura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignatura1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        tfnombredocente.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfceduladocente, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(tfnombredocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarAsignatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarAsignatura1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfceduladocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombredocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(5, 5, 5))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones"));

        comboCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCursoItemStateChanged(evt);
            }
        });

        jLabel5.setText("Curso");

        jLabel6.setText("Calificacion");

        combocalificacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combocalificacionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCurso, 0, 240, Short.MAX_VALUE)
                    .addComponent(combocalificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combocalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check44.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Estudiantes"));

        tablaCalificaicon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Calificacion"
            }
        ));
        jScrollPane1.setViewportView(tablaCalificaicon);

        btnCalificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen41.png"))); // NOI18N
        btnCalificar.setToolTipText("Calificar Estudiante Seleccionado de la Tabla");
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalificar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combocalificacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combocalificacionItemStateChanged
        // TODO add your handling code here:
        try {
            if (comboCurso.getSelectedItem() == null) {
                return;
            }
            if (comboCurso.getSelectedIndex() != 0) {
                Curso curso = controlador.buscarCurso((String) comboCurso.getSelectedItem());
                llenarTabla(curso);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
                    
        }

    }//GEN-LAST:event_combocalificacionItemStateChanged

    private void btnBuscarAsignatura1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarAsignatura1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            if (tfceduladocente.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese la cédula del docente");
            } else {
                Docente docente = controlador.buscarDocente(tfceduladocente.getText());
                if (docente != null) {
                    tfnombredocente.setText(docente.getNombre() + " " + docente.getApellido());
                    llenarComboCurso(docente);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "No hay un docente con la " + "cédula " + tfceduladocente.getText());
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_btnBuscarAsignatura1ActionPerformed

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCalificarActionPerformed
        // TODO add your handling code here:
        try {
            if (tablaCalificaicon.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Seleccione un estudiante");
                return;
            }
            if (combocalificacion.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Seleccione una calificación");
                return;
            }
            double valorNota = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor de la nota"));
            int row = tablaCalificaicon.getSelectedRow();
            DefaultTableModel tabla = (DefaultTableModel) tablaCalificaicon.getModel();
            String cedula = (String) tabla.getValueAt(row, 0);
            Estudiante est = controlador.buscarEstudiante(cedula);
            Curso curso = controlador.buscarCurso((String) comboCurso.getSelectedItem());
            RegistroCurso registro = controlador.buscarRegistroCurso(est, curso);
            Nota nota = new Nota();
            nota.setRegistroCurso(registro);
            nota.setEvaluacion((Evaluacion) combocalificacion.getSelectedItem());
            String notaValor = (String) tabla.getValueAt(row, 3);
            if (notaValor.equals("NC")) {
                nota.setValor(valorNota);
                controlador.crear(nota);
            } else {
                nota.setValor(Double.parseDouble((String) tabla.getValueAt(row, 3)));
                controlador.crear(nota);
            }
            JOptionPane.showMessageDialog(null, "Nota ingresada satisfactoriamente");
        } catch (ExcepcionNegocio ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_btnCalificarActionPerformed

    private void comboCursoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboCursoItemStateChanged
        // TODO add your handling code here:
        try {
            if (comboCurso.getSelectedItem() == null) {
                return;
            }
            if (comboCurso.getSelectedIndex() != 0) {
                Curso curso = controlador.buscarCurso((String) comboCurso.getSelectedItem());
                llenarComboCalificaciones(curso);
            }
//			} else {
//				DefaultTableModel tabla = (DefaultTableModel) tablaCalificaicon.getModel();
//				tabla.setRowCount(0);
//				combocalificacion.removeAllItems();
//			}
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_comboCursoItemStateChanged

    /**
     * método para llenar la tabla con la lista de estudiantes
     *
     * @param curso, el curso al que se le van a ver los estudiantes
     * @throws Exception
     */
    private void llenarTabla(Curso curso) throws Exception {
        List<RegistroCurso> lista = controlador.listarRegistroCursoPorCurso(curso);
        DefaultTableModel tabla = (DefaultTableModel) tablaCalificaicon.getModel();
        tabla.setRowCount(0);
        for (RegistroCurso reg : lista) {
            String cedula = reg.getEstudiante().getCedula();
            String nombre = reg.getEstudiante().getNombre();
            String apellido = reg.getEstudiante().getApellido();
            String nota = "NC";
            if (combocalificacion.getSelectedIndex() != 0) {
                nota = buscarNota(reg, (Evaluacion) combocalificacion.getSelectedItem());
            }
            tabla.addRow(new Object[]{cedula, nombre, apellido, nota});
        }
    }

    /**
     * Método para ver la nota de cada estudiante de un curso
     *
     * @param registro, el registro curso
     * @param eval, la evaluación
     * @return un String con la nota
     * @throws Exception
     */
    private String buscarNota(RegistroCurso registro, Evaluacion eval) throws Exception {
        String valor = "NC";
        Nota nota = controlador.buscarNota(registro, eval);
        if (nota == null) {
            return valor;
        } else {
            valor = ((Double) nota.getValor()).toString();
        }
        return valor;
    }

    /**
     * Método para llenar el combo de cursos
     *
     * @param docente, el docente al que se le buscan los cursos
     * @throws Exception
     */
    private void llenarComboCurso(Docente docente) throws Exception {
        comboCurso.removeAllItems();
        List<Curso> cursos = controlador.listarCursoPorDocente(docente);
        comboCurso.addItem("Seleccione un curso");
        for (Curso curso : cursos) {
            comboCurso.addItem(curso.getCodigo());
        }
    }

    /**
     * Método para llenar el combo de calificaciones
     *
     * @param curso, el curso al que se le buscan las evaluaciones
     * @throws Exception
     */
    private void llenarComboCalificaciones(Curso curso) throws Exception {
        combocalificacion.removeAllItems();
        List<Evaluacion> lista = controlador.listarEvaluacionPorCurso(curso);
        combocalificacion.addItem("Seleccione una calificación");
        for (Evaluacion eval : lista) {
            combocalificacion.addItem(eval);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsignatura1;
    private javax.swing.JButton btnCalificar;
    private javax.swing.JComboBox comboCurso;
    private javax.swing.JComboBox combocalificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCalificaicon;
    private javax.swing.JTextField tfceduladocente;
    private javax.swing.JTextField tfnombredocente;
    // End of variables declaration//GEN-END:variables
}
